spring:
  mode: HTML
  enabled: true
  cache: false
  encoding: UTF-8
　mail:
    host: smtp.example.com
    port: 587
    username: your-email@example.com
    password: your-email-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
