spring:
  thymeleaf:
    mode: HTML
    cache: false
    encoding: UTF-8

  mail:
    host: smtp.mailtrap.io
    port: 587
    username: 3c658ddfdd92a5
    password: f6827ac165ef12
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
